FROM golang:1.24 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o discovery .

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /app/discovery /discovery
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/discovery"]
